--[[
	******************************************************************************
	* @file		  : ...soundHandler.luau
	* @author	  : scrpt2r
	* @date		  : May 12 2026
	* @lastEdit	  : May 13 2026 23:54
	* @brief	  : A modular audio framework built for Roblox developers.
	* @version	  : 0.3.2
	******************************************************************************
	* @attention
	*
	* Copyright © 2026 Axon Corporation.
	* All rights reserved.
	*
	* This software is licensed under terms that can be found in the LICENSE file
	* in the root directory of this software component.
	* If no LICENSE file comes with this software, it is provided AS-IS.
	*
	******************************************************************************
--]]

--// Lib Decleration
return require(script.libs.__main__)
